apiVersion: v1
kind: Secret
metadata:
  name: gcal-sync-sa-key
  namespace: daam-shared
type: Opaque
stringData:
  service-account.json: |
    <create via: oc create secret generic gcal-sync-sa-key
      --from-file=service-account.json=/path/to/key.json
      -n daam-shared>
---
apiVersion: v1
kind: Secret
metadata:
  name: gcal-sync-oauth-token
  namespace: daam-shared
type: Opaque
stringData:
  oauth-token.json: |
    <create via: oc create secret generic gcal-sync-oauth-token
      --from-file=oauth-token.json=oauth-token.json
      -n daam-shared>
